# Generated by Django 5.0.7 on 2024-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pets_no',
            field=models.CharField(default='', help_text='Enter the 4-digit pet number', max_length=4, unique=True),
        ),
    ]
