# Generated by Django 5.0.7 on 2024-07-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0002_pet_pets_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petadopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the pet's name", max_length=250)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('FISH', 'Fish'), ('REPTILES', 'Reptiles'), ('SMALL MAMMAL', 'Small Mammal'), ('OTHER', 'Other')], help_text='Select the species of the pet', max_length=250)),
                ('breed2', models.CharField(blank=True, help_text='Enter the second breed of the pet', max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='Enter the location of the pet', max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Enter the quantity of the pet')),
                ('color', models.CharField(blank=True, help_text='Enter the color of the pet', max_length=50, null=True)),
                ('dob', models.CharField(help_text='Enter the date of birth of the pet', max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Enter the age of the pet in years', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the weight of the pet', max_digits=5, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Enter the gender of the pet', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of the pet', null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the pet', null=True, upload_to='pets/')),
                ('is_adopted', models.BooleanField(default=False, help_text='Mark if the pet has been adopted')),
                ('available_from', models.DateField(blank=True, help_text='Date when the pet became available for adoption', null=True)),
                ('map', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the pet record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the pet record was last updated')),
                ('breed', models.ForeignKey(blank=True, help_text='Select the breed of the pet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petsadoption', to='Paradiseapp.breed')),
            ],
            options={
                'verbose_name': 'Petadopt',
                'verbose_name_plural': 'Petsadoption',
                'ordering': ['-created_at'],
            },
        ),
    ]
