# Generated by Django 5.0.7 on 2024-07-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0003_petadopt'),
    ]

    operations = [
        migrations.CreateModel(
            name='petsadopt_additional_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paradiseapp.pet')),
            ],
        ),
    ]
