# Generated by Django 5.0.7 on 2024-07-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0004_petsadopt_additional_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsadopt_additional_image',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paradiseapp.petadopt'),
        ),
    ]
