# Generated by Django 5.0.7 on 2024-07-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0005_alter_petsadopt_additional_image_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_adopted',
        ),
    ]
