# Generated by Django 5.0.7 on 2024-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0006_remove_pet_is_adopted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petadopt',
            options={},
        ),
    ]
