# Generated by Django 5.0.7 on 2024-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0007_alter_petadopt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsadopt_additional_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petsadopt/'),
        ),
    ]
