# Generated by Django 5.0.7 on 2024-07-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0009_adoptionrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
