# Generated by Django 5.0.7 on 2024-07-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0011_adoptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pets_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
