# Generated by Django 5.0.7 on 2024-07-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0012_alter_adoptionrequest_pets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
