# Generated by Django 5.0.7 on 2024-07-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0013_alter_adoptionrequest_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
