# Generated by Django 5.0.7 on 2024-07-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0014_delete_adoptionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('species', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pets_no', models.CharField(blank=True, max_length=4, null=True)),
                ('pets_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paradiseapp.petadopt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
