# Generated by Django 5.0.7 on 2024-07-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0015_adoptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='pets_id',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='pets_no',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='species',
            field=models.CharField(max_length=50),
        ),
    ]
