# Generated by Django 5.0.7 on 2026-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0017_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=555, null=True, unique=True),
        ),
    ]
