# Generated by Django 5.0.7 on 2026-02-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0018_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petadopt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Petadopt', 'verbose_name_plural': 'Petsadoption'},
        ),
    ]
