# Generated by Django 5.0.7 on 2026-02-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paradiseapp', '0019_alter_petadopt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadopt',
            name='pets_no',
            field=models.CharField(default='', help_text='Enter the 4-digit pet number', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='petadopt',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
